CREATE TABLE IF NOT EXISTS events (
    event_id SERIAL PRIMARY KEY,
    hook_id INTEGER NOT NULL,
    payload JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (hook_id) REFERENCES webhooks(hook_id) ON DELETE CASCADE
);